spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/{application}

server:
  port: 8888

logging:
  level:
    com.dzinevich.config: debug