spring:
  application:
    name: discovery
  security:
    user:
      name: netflix
      password: eureka

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix.discovery: OFF
    com.netflix.eureka: OFF
